name: Build And Test
run-name: ${{ github.actor }} wants to build and test
on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: java -version
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to build and test the project on the runner."
      - run: mvn clean install -PCI
      - run: echo "This job's status is ${{ job.status }}."